# argocd-install.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-installer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd
    spec:
      containers:
        - name: argocd-installer
          image: argoproj/argocd:v2.1.3
          command: ["/bin/sh"]
          args: ["-c", "argocd-util cmd --install | sh"]
