# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: argocd-server
    spec:
      containers:
        - name: argocd-server
          image: argoproj/argocd:v2.1.3
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /app/config
              name: argocd-config
      volumes:
        - name: argocd-config
          configMap:
            name: argocd-config
